### ISSUE TITLE
Swift Tour: Sessão de Controle de Fluxo tem um exemplo confuso

### ISSUE THREAD

**Issue by GabrielaBezerra** [AcademyIFCE/swift-book-markdown#206]
A parte de Controle de Fluxo tem um exemplo de código que na prática foi confuso para os alunos que estudaram por ele.
Com isso em mente, seria bom adicionar um ou dois comentários em português no exemplo explicando melhor o que eles fazem.

**Comment by SarahMadalena** [comment]
Para melhorar a ambiguidade do código que trata sobre **if** e **let**, acredito que a melhor forma de ser feita é a seguinte:
```swift
//Código 1
var optionalString: String? = "Hello"
print(optionalString == nil)
// Imprime "false"

//Código 2
var optionalName: String? = "John Appleseed"
var greeting = "Hello!"
if let name = optionalName {
    greeting = "Hello, \(name)"
}
//Imprime "Hello, John Appleseed
```
